name: Docker Build

on:
  push:
    branches:
      - main
      - dev
      - staging
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 设置 QEMU 支持多架构（可选，多平台构建）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3️⃣ 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ 登录 DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: qianwanbie  # 你的 DockerHub Username，例如 qianwanbie
          password: DockerHub Access Token  # DockerHub Access Token

      # 5️⃣ 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .                   # Dockerfile 所在目录
          file: ./Dockerfile           # Dockerfile 路径
          push: true                   # 构建完成后推送镜像
          tags: ${{ secrets.DOCKER_USERNAME }}/ml-digit-recognition:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ml-digit-recognition:latest
          cache-to: type=inline
